version: '2'

services:
  kafka_metrics_agent:
    image: krkr/kafka-metrics-agent
    container_name: kafka-metrics-agent
    ports:
      - 4242:4242
    command:
      -kafka-brokers=$KAFKA_BROKERS
      -kafka-jmx-password=$KAFKA_JMX_PASSWORD
      -opentsdb-url=$OPENTSDB_URL
      -opentsdb-token=$OPENTSDB_TOKEN

